"""Typer CLI application for promptlint.

Provides ``check``, ``watch``, ``rules``, ``init``, and ``init-pipeline``
commands.  Registered as the ``promptlint`` entry point via pyproject.toml.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Optional

import typer
from rich.console import Console

from promptlint.config import load_config
from promptlint.core.engine import (
    get_all_pipeline_rules,
    get_all_rules,
    lint_file,
    lint_pipeline,
)
from promptlint.core.fixer import apply_fixes
from promptlint.core.parser import parse_file, parse_pipeline_manifest, parse_stdin
from promptlint.core.reporter import report
from promptlint.models import Severity

# ---------------------------------------------------------------------------
# App and console
# ---------------------------------------------------------------------------

app = typer.Typer(
    name="promptlint",
    help="Static analysis tool for LLM prompts.",
    add_completion=False,
    no_args_is_help=True,
)

_console = Console()
_err_console = Console(stderr=True)

# Prompt file extensions recognised when walking directories.
PROMPT_EXTENSIONS: frozenset[str] = frozenset({".txt", ".md", ".yaml", ".yml", ".json"})

_PIPELINE_MANIFEST = ".promptlint-pipeline.yaml"

# Category mapping: derive from rule_id prefix.
_RULE_ID_CATEGORY: dict[str, str] = {
    "PL00": "token",
    "PL01": "system",
    "PL02": "formatting",
    "PL03": "variable",
    "PL04": "pipeline",
    "PL05": "hallucination",
    "PL06": "security",
    "PL07": "smell",
    "PL08": "gate",
}


def _category_for_rule(rule_id: str) -> str:
    """Return the human-readable category for a rule ID."""
    prefix = rule_id[:4] if len(rule_id) >= 4 else rule_id
    return _RULE_ID_CATEGORY.get(prefix, "plugin")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _collect_prompt_files(path: Path) -> list[Path]:
    """Recursively collect prompt files under *path*."""
    files: list[Path] = []
    for child in sorted(path.rglob("*")):
        if child.is_file() and child.suffix.lower() in PROMPT_EXTENSIONS:
            files.append(child)
    return files


def _load_baseline(baseline_path: Path) -> set[tuple[str, str, int | None, str]]:
    """Load a baseline JSON report and return a set of violation keys."""
    try:
        data = json.loads(baseline_path.read_text(encoding="utf-8"))
    except Exception as exc:
        _err_console.print(f"[red]Error reading baseline: {exc}[/red]")
        raise typer.Exit(code=2) from exc

    keys: set[tuple[str, str, int | None, str]] = set()
    if isinstance(data, list):
        for item in data:
            keys.add((
                item.get("rule_id", ""),
                item.get("path", ""),
                item.get("line"),
                item.get("message", ""),
            ))
    return keys


def _default_config_yaml() -> str:
    """Return the default ``.promptlint.yaml`` scaffold content."""
    return """\
# promptlint configuration
# Docs: https://github.com/promptlint/promptlint

# Model profile (auto-sets context window + tokenizer)
# model: gpt-4

# Tokenizer
tokenizer:
  encoding: cl100k_base

# Token budget thresholds
token_budget:
  warn_threshold: 2048
  error_threshold: 4096
  system_prompt_threshold: 1024
  stop_word_ratio: 0.60

# Formatting
formatting:
  max_line_length: 500
  repetition_threshold: 3

# Per-rule severity overrides (rule_id: error|warning|info|ignore)
rules: {}

# Globally ignored rules
ignore: []

# File glob patterns to exclude
exclude: []

# Plugin directories
plugins: []
"""


def _scaffold_pipeline_yaml(directory: Path) -> str:
    """Scan *directory* for prompt files and produce a pipeline manifest."""
    files = _collect_prompt_files(directory)
    stages: list[str] = []
    for i, f in enumerate(files):
        rel = f.relative_to(directory)
        name = f.stem.replace(" ", "-").lower()
        entry = f"  - name: {name}\n    file: {rel}"
        if i > 0:
            prev_name = files[i - 1].stem.replace(" ", "-").lower()
            entry += f"\n    depends_on:\n      - {prev_name}"
        stages.append(entry)

    stages_block = "\n".join(stages) if stages else "  []"
    return f"""\
# promptlint pipeline manifest
# Generated by: promptlint init-pipeline

name: my-pipeline

stages:
{stages_block}
"""


# ---------------------------------------------------------------------------
# check command
# ---------------------------------------------------------------------------

@app.command()
def check(
    path: str = typer.Argument(
        ...,
        help="File or directory to lint. Use '-' to read from stdin.",
    ),
    config: Optional[Path] = typer.Option(
        None, "--config", "-c",
        help="Path to .promptlint.yaml config file.",
        exists=True, dir_okay=False,
    ),
    format: str = typer.Option(
        "text", "--format", "-f",
        help="Output format: text, json, github.",
    ),
    input_format: Optional[str] = typer.Option(
        None, "--input-format",
        help="Force input format for stdin: text, md, yaml, json.",
    ),
    model: Optional[str] = typer.Option(
        None, "--model", "-m",
        help="Model profile name (overrides config file).",
    ),
    select: Optional[str] = typer.Option(
        None, "--select",
        help="Comma-separated rule IDs to enable.",
    ),
    ignore: Optional[str] = typer.Option(
        None, "--ignore",
        help="Comma-separated rule IDs to suppress.",
    ),
    min_severity: str = typer.Option(
        "info", "--min-severity",
        help="Minimum severity to report: info, warning, error.",
    ),
    no_color: bool = typer.Option(
        False, "--no-color",
        help="Disable rich color output.",
    ),
    quiet: bool = typer.Option(
        False, "--quiet", "-q",
        help="Only print errors, suppress warnings and info.",
    ),
    stats: bool = typer.Option(
        False, "--stats",
        help="Print a rule-hit summary table after violations.",
    ),
    fix: bool = typer.Option(
        False, "--fix",
        help="Apply auto-fixes for fixable violations.",
    ),
    dry_run: bool = typer.Option(
        False, "--dry-run",
        help="With --fix: preview fixes without writing.",
    ),
    pipeline: bool = typer.Option(
        False, "--pipeline",
        help="Treat directory as a pipeline (requires manifest).",
    ),
    baseline: Optional[Path] = typer.Option(
        None, "--baseline",
        help="Path to a previous JSON report; only show new violations.",
        exists=True, dir_okay=False,
    ),
    cache: bool = typer.Option(
        False, "--cache",
        help="Enable token count caching.",
    ),
) -> None:
    """Lint one or more prompt files or directories."""
    console = Console(no_color=no_color)

    # Override min_severity when --quiet
    effective_min_severity = "error" if quiet else min_severity

    # Build CLI overrides dict
    cli_overrides: dict[str, object] = {}
    if model is not None:
        cli_overrides["model"] = model
    if ignore is not None:
        cli_overrides["ignore"] = ignore
    if select is not None:
        cli_overrides["select"] = [r.strip() for r in select.split(",")]

    # ------------------------------------------------------------------
    # Resolve target path
    # ------------------------------------------------------------------
    reading_stdin = path == "-"

    if reading_stdin:
        # Read from stdin
        try:
            stdin_content = sys.stdin.read()
        except Exception as exc:
            _err_console.print(f"[red]Error reading stdin: {exc}[/red]")
            raise typer.Exit(code=2) from exc

        fmt = input_format or "text"
        try:
            prompt_file = parse_stdin(stdin_content, fmt)
        except Exception as exc:
            _err_console.print(f"[red]Parse error: {exc}[/red]")
            raise typer.Exit(code=2) from exc

        cfg = load_config(Path.cwd(), cli_overrides or None)
        try:
            violations = lint_file(prompt_file, cfg, effective_min_severity)
        except Exception as exc:
            _err_console.print(f"[red]Lint error: {exc}[/red]")
            raise typer.Exit(code=2) from exc

        output = report(violations, format=format, stats=stats)
        if output:
            console.print(output, highlight=False)
        raise typer.Exit(code=1 if violations else 0)

    # Non-stdin: resolve the path on disk
    target = Path(path).resolve()
    if not target.exists():
        _err_console.print(f"[red]Path not found: {path}[/red]")
        raise typer.Exit(code=2)

    # Load config (use explicit --config or auto-discover)
    try:
        if config is not None:
            # Read the explicit config, then apply CLI overrides
            cfg = load_config(config.parent, cli_overrides or None)
        else:
            cfg = load_config(target, cli_overrides or None)
    except Exception as exc:
        _err_console.print(f"[red]Config error: {exc}[/red]")
        raise typer.Exit(code=2) from exc

    # Determine selected rules (for filtering)
    selected_ids: set[str] | None = None
    if select is not None:
        selected_ids = {r.strip() for r in select.split(",")}

    # ------------------------------------------------------------------
    # Pipeline mode
    # ------------------------------------------------------------------
    if pipeline:
        manifest_path: Path | None = None
        if target.is_file() and target.name == _PIPELINE_MANIFEST:
            manifest_path = target
        elif target.is_dir():
            candidate = target / _PIPELINE_MANIFEST
            if candidate.is_file():
                manifest_path = candidate

        if manifest_path is None:
            _err_console.print(
                f"[red]Pipeline manifest ({_PIPELINE_MANIFEST}) not found.[/red]"
            )
            raise typer.Exit(code=2)

        try:
            pipeline_obj = parse_pipeline_manifest(manifest_path)
        except Exception as exc:
            _err_console.print(f"[red]Pipeline parse error: {exc}[/red]")
            raise typer.Exit(code=2) from exc

        try:
            violations = lint_pipeline(pipeline_obj, cfg, effective_min_severity)
        except Exception as exc:
            _err_console.print(f"[red]Lint error: {exc}[/red]")
            raise typer.Exit(code=2) from exc

        # Filter by --select
        if selected_ids is not None:
            violations = [v for v in violations if v.rule_id in selected_ids]

        # Apply baseline filtering
        if baseline is not None:
            baseline_keys = _load_baseline(baseline)
            violations = [
                v for v in violations
                if (v.rule_id, str(v.path), v.line, v.message) not in baseline_keys
            ]

        # Auto-fix
        if fix:
            all_rules_list = get_all_rules(cfg)
            fix_lines = apply_fixes(violations, all_rules_list, dry_run=dry_run)
            for line in fix_lines:
                console.print(line, highlight=False)

        output = report(violations, format=format, stats=stats)
        if output:
            console.print(output, highlight=False)
        raise typer.Exit(code=1 if violations else 0)

    # ------------------------------------------------------------------
    # Single file or directory mode
    # ------------------------------------------------------------------
    files_to_lint: list[Path] = []
    if target.is_file():
        files_to_lint.append(target)
    elif target.is_dir():
        files_to_lint = _collect_prompt_files(target)
        if not files_to_lint:
            _err_console.print(
                f"[yellow]No prompt files found in {target}[/yellow]"
            )
            raise typer.Exit(code=0)
    else:
        _err_console.print(f"[red]Path is neither a file nor directory: {path}[/red]")
        raise typer.Exit(code=2)

    all_violations = []
    for file_path in files_to_lint:
        try:
            prompt_file = parse_file(file_path)
        except Exception as exc:
            _err_console.print(
                f"[red]Parse error in {file_path}: {exc}[/red]"
            )
            continue

        try:
            file_violations = lint_file(prompt_file, cfg, effective_min_severity)
        except Exception as exc:
            _err_console.print(
                f"[red]Lint error in {file_path}: {exc}[/red]"
            )
            continue

        all_violations.extend(file_violations)

    # Filter by --select
    if selected_ids is not None:
        all_violations = [v for v in all_violations if v.rule_id in selected_ids]

    # Apply baseline filtering
    if baseline is not None:
        baseline_keys = _load_baseline(baseline)
        all_violations = [
            v for v in all_violations
            if (v.rule_id, str(v.path), v.line, v.message) not in baseline_keys
        ]

    # Auto-fix
    if fix:
        all_rules_list = get_all_rules(cfg)
        fix_lines = apply_fixes(all_violations, all_rules_list, dry_run=dry_run)
        for line in fix_lines:
            console.print(line, highlight=False)

    output = report(all_violations, format=format, stats=stats)
    if output:
        console.print(output, highlight=False)
    raise typer.Exit(code=1 if all_violations else 0)


# ---------------------------------------------------------------------------
# watch command
# ---------------------------------------------------------------------------

@app.command()
def watch(
    path: str = typer.Argument(
        ...,
        help="File or directory to watch.",
    ),
    config: Optional[Path] = typer.Option(
        None, "--config", "-c",
        help="Path to .promptlint.yaml config file.",
        exists=True, dir_okay=False,
    ),
    min_severity: str = typer.Option(
        "warning", "--min-severity",
        help="Minimum severity to report during watch.",
    ),
    clear: bool = typer.Option(
        True, "--clear/--no-clear",
        help="Clear terminal before each re-lint.",
    ),
) -> None:
    """Monitor files for changes and re-lint on save."""
    try:
        from watchfiles import watch as watchfiles_watch
    except ImportError:
        _err_console.print(
            "[red]watchfiles is required for watch mode. "
            "Install it with: pip install watchfiles[/red]"
        )
        raise typer.Exit(code=2)

    target = Path(path).resolve()
    if not target.exists():
        _err_console.print(f"[red]Path not found: {path}[/red]")
        raise typer.Exit(code=2)

    console = Console()

    # Load config once
    try:
        if config is not None:
            cfg = load_config(config.parent)
        else:
            cfg = load_config(target)
    except Exception as exc:
        _err_console.print(f"[red]Config error: {exc}[/red]")
        raise typer.Exit(code=2) from exc

    def _is_prompt_file(p: Path) -> bool:
        return p.suffix.lower() in PROMPT_EXTENSIONS

    def _lint_and_display(file_path: Path) -> None:
        """Lint a single file and display results."""
        if clear:
            console.clear()
        console.rule(f"[bold cyan]promptlint watch[/bold cyan] — {file_path.name}")
        try:
            prompt_file = parse_file(file_path)
            violations = lint_file(prompt_file, cfg, min_severity)
            output = report(violations, format="text", stats=False)
            console.print(output, highlight=False)
        except Exception as exc:
            console.print(f"[red]Error: {exc}[/red]")

    # Initial lint
    if target.is_file():
        _lint_and_display(target)
    else:
        console.print(
            f"[bold cyan]Watching[/bold cyan] {target} for changes...",
            highlight=False,
        )

    # Determine watch path
    watch_path = target if target.is_dir() else target.parent

    try:
        for changes in watchfiles_watch(watch_path):
            for _change_type, changed_path_str in changes:
                changed = Path(changed_path_str)
                if _is_prompt_file(changed) and changed.is_file():
                    _lint_and_display(changed)
    except KeyboardInterrupt:
        console.print("\n[bold cyan]Watch stopped.[/bold cyan]")
        raise typer.Exit(code=0)


# ---------------------------------------------------------------------------
# rules command
# ---------------------------------------------------------------------------

@app.command()
def rules(
    format: str = typer.Option(
        "text", "--format",
        help="Output format: text or json.",
    ),
    category: Optional[str] = typer.Option(
        None, "--category",
        help=(
            "Filter by category: token, system, formatting, variable, "
            "pipeline, hallucination, security, smell, gate, plugin."
        ),
    ),
) -> None:
    """List all available lint rules."""
    from promptlint.rules.base import BasePipelineRule, BaseRule

    all_file_rules = get_all_rules()
    all_pipeline_rules = get_all_pipeline_rules()

    # Combine into a unified list of dicts
    rule_entries: list[dict[str, object]] = []

    for r in all_file_rules:
        rule_entries.append({
            "rule_id": r.rule_id,
            "name": r.name,
            "severity": r.default_severity.value,
            "fixable": getattr(r, "fixable", False),
            "category": _category_for_rule(r.rule_id),
        })

    for r in all_pipeline_rules:
        rule_entries.append({
            "rule_id": r.rule_id,
            "name": r.name,
            "severity": r.default_severity.value,
            "fixable": False,
            "category": _category_for_rule(r.rule_id),
        })

    # Sort by rule_id
    rule_entries.sort(key=lambda e: str(e["rule_id"]))

    # Filter by category
    if category is not None:
        cat_lower = category.strip().lower()
        rule_entries = [e for e in rule_entries if e["category"] == cat_lower]

    if format.strip().lower() == "json":
        _console.print(json.dumps(rule_entries, indent=2), highlight=False)
        return

    # Text format
    if not rule_entries:
        _console.print("No rules found.", highlight=False)
        return

    _console.print("[bold]Available rules:[/bold]\n")
    for e in rule_entries:
        fixable_tag = " [green](fixable)[/green]" if e["fixable"] else ""
        sev = str(e["severity"])
        if sev == "error":
            sev_styled = f"[bold red]{sev}[/bold red]"
        elif sev == "warning":
            sev_styled = f"[bold yellow]{sev}[/bold yellow]"
        else:
            sev_styled = f"[bold blue]{sev}[/bold blue]"

        _console.print(
            f"  {e['rule_id']}  {e['name']:<40s} {sev_styled}  "
            f"[dim]{e['category']}[/dim]{fixable_tag}"
        )


# ---------------------------------------------------------------------------
# init command
# ---------------------------------------------------------------------------

@app.command()
def init() -> None:
    """Scaffold a .promptlint.yaml with defaults in the current directory."""
    target = Path.cwd() / ".promptlint.yaml"
    if target.exists():
        _err_console.print(
            f"[yellow]{target} already exists. Remove it first to re-scaffold.[/yellow]"
        )
        raise typer.Exit(code=1)

    target.write_text(_default_config_yaml(), encoding="utf-8")
    _console.print(f"[green]Created {target}[/green]")


# ---------------------------------------------------------------------------
# init-pipeline command
# ---------------------------------------------------------------------------

@app.command(name="init-pipeline")
def init_pipeline() -> None:
    """Scaffold a .promptlint-pipeline.yaml by scanning for prompt files."""
    target = Path.cwd() / _PIPELINE_MANIFEST
    if target.exists():
        _err_console.print(
            f"[yellow]{target} already exists. Remove it first to re-scaffold.[/yellow]"
        )
        raise typer.Exit(code=1)

    content = _scaffold_pipeline_yaml(Path.cwd())
    target.write_text(content, encoding="utf-8")
    _console.print(f"[green]Created {target}[/green]")


# ---------------------------------------------------------------------------
# Entry point (allows ``python -m promptlint.cli``)
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    app()
